### ISSUE TITLE
No output whatsoever?

### ISSUE THREAD

**Issue by brantondemoss** [dejo7374/Jones_CSCI2270_FinalProject#4]
The program runs fine... but there is no user interaction or i/o at all. Have I done something wrong? It seems like you build everything correctly and run through some things, but as far as the user is concerned nothing seems to happen.

Also, the Creature class implementation is empty. Why?

**Comment by dejo7374** [comment]
No, you've done nothing wrong. I attempted to set up the graph and then wanted to add a way for the character to move through the graph but had no idea where to start. So I tried to walk it back, but then I ended up with a program that doesn't do anything.
